openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://0.0.0.0:4010
paths:
  /item:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemPreview'
  /item/{itemId}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemOverview'

components:
  schemas:
    itemPreview:
      type: object
      properties:
        order:
          type: number
        item:
          type: object
          properties:
            itemId:
              type: string
            properties:
              type: object
              properties:
                name: 
                  type: string
                price:
                  type: number
                  format: bouble
                details:
                  type: object
                  properties:
                    status:
                      type: string
      example:
        - itemId: f6d655da-6fff-11ee-b3bc-e86a6465f38b
          properties:
          name: クラウディ・エンチャント
          price: 2480
          details:
            status: Available
        - itemId: a64f1463-abd2-11ee-a4c7-e86a6465f38b
          properties:
            name: ゴールデン・ハーモニー
            price: 9800
            details:
              status: Available
    itemOverview:
      type: object
      properties:
        itemId:
          type: string
        properties:
          type: object
          properties:
            name:
              type: string
            price:
              type: number
              format: double
            size:
                type: number
        details:
          type: object
          properties:
            status:
              type: string
            stock:
              type: number
            description:
              type: string
            tags: 
              type: object
              properties:
                color:
                  type: string
                series:
                  type: string
        manufacturer:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
      example:
        itemId: a64f1463-abd2-11ee-a4c7-e86a6465f38b
        properties:
          name: ゴールデン・ハーモニー
          price: 9800
          details:
            status: Available
            stock: 1
            size: 16
            description: シトリンは、豊かさと繁栄を象徴するクリスタルと...
            tags:
              color: 黄
              series: Lucky Aura
          manufacturer:
            name: kumi
            description: 心を込めた商品を制作しております...
